In [36]:
import numpy as np          

In [37]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr[6]

6

In [39]:
arr[0]

0

In [40]:
arr_a = np.arange(1,11)
arr_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
boool = arr_a>5

In [42]:
arr_a[boool]

array([ 6,  7,  8,  9, 10])

In [43]:
arr_a>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])